version: "3.9"

services:
  machine:
    image: cartesi/dapp:${DAPP_NAME:?undefined DAPP_NAME}-devel-machine
    command: xxd -c 256 -p latest/hash; sleep 3
    volumes:
      - machine:/var/opt/cartesi/machine-snapshots

  contract-chainlink:
    build: ./contracts
    command: ["mkdir -p deployments/${NETWORK:?undefined NETWORK} && forge create --rpc-url '${RPC_URL:?undefined RPC_URL}' --mnemonic '${MNEMONIC:?undefined MNEMONIC}' --json /opt/contracts/src/${NETWORK:?undefined NETWORK}/token-prices-chainlink.sol:TokenPricesChainlinkV3 | tee deployments/${NETWORK:?undefined NETWORK}/TokenPricesChainlinkV3.json"]
    volumes:
      - ./deployments:/opt/contracts/deployments

  contract-uniswap:
    build: ./contracts
    depends_on:
      contract-chainlink:
        condition: service_completed_successfully
    command: ["mkdir -p deployments/${NETWORK:?undefined NETWORK} && forge create --rpc-url '${RPC_URL:?undefined RPC_URL}' --mnemonic '${MNEMONIC:?undefined MNEMONIC}' --json /opt/contracts/src/${NETWORK:?undefined NETWORK}/token-prices-uniswap.sol:TokenPricesUniswapV3 | tee deployments/${NETWORK:?undefined NETWORK}/TokenPricesUniswapV3.json"]
    volumes:
      - ./deployments:/opt/contracts/deployments

  authority-deployer:
    image: cartesi/rollups-hardhat:1.0.0
    depends_on:
      contract-chainlink:
        condition: service_completed_successfully
      contract-uniswap:
        condition: service_completed_successfully
    command:
      [
        "deploy",
        "--tags",
        "Authority",
        "--network",
        "${NETWORK:?undefined NETWORK}",
        "--export",
        "/home/node/rollups.json",
      ]
    volumes:
      - ./deployments/${NETWORK:?undefined NETWORK}:/home/node
    environment:
      - MNEMONIC=${MNEMONIC:?undefined MNEMONIC}
      - RPC_URL=${RPC_URL:?undefined RPC_URL}

  dapp-deployer:
    build: ./build/testnet-dapp-deployer
    depends_on:
      machine:
        condition: service_started
      authority-deployer:
        condition: service_completed_successfully
    volumes:
      - machine:/var/opt/cartesi/machine-snapshots:ro
      - ./deployments:/deployments
      - ./build:/build
    environment:
      - MNEMONIC=${MNEMONIC:?undefined MNEMONIC}
      - NETWORK=${NETWORK:?undefined NETWORK}
      - RPC_URL=${RPC_URL:?undefined RPC_URL}
      - DAPP_NAME=${DAPP_NAME:?undefined DAPP_NAME}

volumes:
  machine: {}